### ISSUE TITLE
Incognito assistance

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Tanoa-Takedown#11]
Want to have someone look over the map and give me some ideas for where to place markers and areas to create zones relating to the incognito script.

**Comment by FoxKilo** [comment]
Sosovu Island
069 071 -Airport Hangar
All religious buildings
Docks

Basically anywhere where normal infantry can't go such as HQ buildings, secret places, high value. Or any places you don't want people to ambush

**Comment by coachwn** [comment]
Hadn't thought about the docks but that is a good idea.

**Comment by coachwn** [comment]
Working...sorta...needs to be kept track of and tweaked as we move ahead. Add new classnames for next updates regarding spawn gear for Molokous, security elements of Kutu and Bolo elements.

**Comment by coachwn** [comment]
Issues with players getting stuck in incognito mode. Jebudiah reported today that he went from independent to civilian mode then back to independent and then after about 30 minutes got stuck in incognito mode until he player exited and returned to the server almost immediately.

With Incognito reporting to other enemies in the area I am wondering if VCOM has an issue with this as well. We need to investigate this further and run this script on a vanilla only mission then add in VCOM and ALiVE.

**Comment by 1ncontinentia** [comment]
Hi dudes, just got the link to this thread. If you could get a repro in vanilla + alive (don't worry about vanilla only as I made the script for ALiVE so if that's borked, it's a bug), then please let me know in [this](https://github.com/1ncontinentia/Incon-Undercover/issues/28) thread and I'll try to get it sorted as soon as possible. As for a VCOM incompatibility, again that's good to know if there are any issues. It's one of the only AI mods I didn't test extensively with. I can't guarantee a fix for that though but I'll try. 

Also, the more detail, the easier I can narrow the issue down (how long was the person spotted? Spotted by asym or reg or both? Spotted and seen returning fire? Respawn? Anything else?).

**Comment by coachwn** [comment]
I think I can answer most of the last few questions.

1. Player was seen as incog while returning fire against regular enemy forces; this lasted for about 3-4 hours yesterday.
2. We do not have an Asym setup at all for our OPFOR; they are simply chinese forces active in an occupation mode against our indy forces who are the insurgents. 
3. Player had respawned at least once and had gone from "acting suspiciously" to incog at least one time. 
4. The incog lasted through several firefights and was while player had pieces and parts of enemy gear on.

As for the VCOM incompatibility...that is simply conjecture on my part at this time. I am working on a test mission with vanilla + ALiVE now and should have some results and a test mission later this afternoon/evening.

**Comment by 1ncontinentia** [comment]
So just to check, the unit gets stuck as a civilian and enemies ignore it no matter what it does? If so, I have a feeling I've encountered it once before. What seemed to have happened that time (I couldn't reproduce it) was that the engine suddenly decided that the unit was now a civilian. So the script still worked as it should but the engine started reverting the unit to civilian rather than it's underlying side. If that's the case, it should be fairly rare but it's an engine bug rather than one I can do anything about. If it happens all the time, hopefully it isn't what I'm describing.

**Comment by coachwn** [comment]
Exactly, Yeah its happening quite regularly and with different players.

**Comment by 1ncontinentia** [comment]
Okay, well I'm hoping there's a bug on my end in that case as it hasn't happened to me during my test missions. Let me know when you have a repro mission and I'll try to figure it out.

**Comment by coachwn** [comment]
Going to close this since we are pulling the scripts out of our mission now that we are beyond the need for them in our mission at this time.
