### ISSUE TITLE
Add respawn loadout sqf's for SOAR and JFD units.

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Tanoa-Takedown#12]
Add in the respawn script for units above to make sure they respawn with gear.

**Comment by FoxKilo** [comment]
loadouts are config'd properly so don't know why they're not respawning with gear....check init on player

**Comment by coachwn** [comment]
Yeah thanks for pointing that out yesterday. Now I am tossing an error for PB6 tossing an error on load. Need to test rest of TF Siren loadouts. PB6 now not respawing at all.

**Comment by coachwn** [comment]
Continue to look at why units are showing AI when you log off.
