### ISSUE TITLE
Change up MELB and ASDG to utilize RHS:USAF mod

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Tanoa-Takedown#13]
Redo of mission mods to add in RHS:USAF along with the RHS compat file to ensure a proper working MkV SOC Boat. Found a small bug that when players ejected from boat they were unable to get into any slot or they had a black screen crash of the game and it required a restart of the computer.

**Comment by FoxKilo** [comment]
So just to confirm you're not getting rid of those 2 mods, just using RHS to bridge the gap?

**Comment by coachwn** [comment]
The ASDG and standalone MELB are removed for RHSUSAF which allows eglm pistol slot GL now.

**Comment by coachwn** [comment]
After testing last night they appear to be functioning properly. Closing this one.
