### ISSUE TITLE
Possible need for moving TF Siren location?

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Tanoa-Takedown#14]
As much as I want to create reasons for guys to be spread around and to find ways to communicate with each other. The starting location could be problematic in the long term.

**Comment by FoxKilo** [comment]
I get the blufor slots, but can you define the different IND groups and who's supposed to fill them? Then I can take a look at what the logistics are going to be like.

**Comment by coachwn** [comment]
IND is everyone else....Bolo is Cav command with Kutu as the overall command group and Molokous as the rest of Cav. Supply is basically handled with whatever they can scavenge and take from PLA forces without getting destroyed. Limited supply from the TF Siren in the way of launchers and assistance in training and taking down objectives.

**Comment by coachwn** [comment]
Not going to move TF Siren location or anyone else. Limited areas only lead to quicker exposure and earlier deaths by all participants.
