### ISSUE TITLE
Test Whitelist

### ISSUE THREAD

**Issue by FoxKilo** [Spearhead-Gaming-Milsim/Tanoa-Takedown#16]
Lines 15 - 41 of init is a whitelist code for slots by GUID, pulled from [BI](https://forums.bistudio.com/forums/topic/174726-player-slot-specific-whitelisting-for-trained-members-and-admins/)

Need to create whitelist.txt and add GUIDs for all concerned.

**Comment by coachwn** [comment]
I think this came from the Incognito scripts; not sure if it is though since I started testing this and want to see if it works. I may pull that out at this time so we can take a look at fixing it for long term usage.

**Comment by FoxKilo** [comment]
definitely not from incognito scripts as i've searched all his github for it....this was taken from the BI forum post I linked i.e google.

The rest of the incognito scripts are somewhat configured but need working on, depending on how you want people to play the game. I can help with that.

**Comment by coachwn** [comment]
No clue what it is for...I might have been looking at a way to lock the slots for the Bolo and Kutu teams but I have zero idea why its in there. Think it might need to be pulled out.

**Comment by FoxKilo** [comment]
Seems like the likely thing. All that needs to be done is the units defined in the code and the whitelist.txt adding to the root server folder. Looks promising but can't test it locally.

**Comment by coachwn** [comment]
Removed whitelist...will not add unless it is 100% necessary.
