### ISSUE TITLE
Testing of 80% version

### ISSUE THREAD

**Issue by FoxKilo** [Spearhead-Gaming-Milsim/Tanoa-Takedown#17]
This relates to bugs/settings in the 80% v2 currently up on the test server that need to go into v3.

- [x] ACE

 

- [x] Modules:
- Place Advanced Fatigue + configure (1, 1.5, 1, 1)
- Place Map + configure
- Place Map Gestures
- Place Map Gestures - Group Settings
- Place Weather if needed
- Place Zeus Settings + configure
- Repair & Rearm not assigned to vics or buildings.
- Spare parts not synced to connex/store box

- [x] Medical Settings:
- Reconfigure Advanced Medical Settings module
- Place Basic Medical Settings module + configure
- Place Medical Settings module + configure
- Set Medic Class not put in player inits
- Set Medical Facility not synced to anything

- [x] Game Master:
- Game Master module from "Gamemodes" interfering with normal operation. Does not allow any actions in zeus. Query it's usage?

- [x] TFAR:
- TS channel not set in module

- [x] Civilians:
- Consider adding ambient vics via ambient module or civ population module.

- [x] Storage:
- Add boxes near businesses that IND can pick up and use for storage.

- [x] Logistics:
- Consider Civ motorboats on coastlines to enable scattered groups logistic access.

- [x] Respawn:
- Select respawn location is selected, interrupting the custom position process.

**Comment by coachwn** [comment]
_All Map Gestures and Map placement_: Already done and set

_Place Weather if needed_: Already in and set

_Place Zeus Settings + configure_: Already done 

_Repair & Rearm not assigned to vics or buildings. Spare parts not synced to connex/store box._: Already set to PLA vehicles. TF Siren will be resupplied as needed with extremely limited resupply of vehicles. Repairs will be effected via toolkits in the field.

_Game Master module from "Gamemodes" interfering with normal operation. Does not allow any actions in zeus. Query it's usage?_: Gamemaster shouldn't be creating problems on that end. I haven't had any issues with action in Zeus. Anything specific to look for in the mission and see what isn't working?

_Reconfigure Advanced Medical Settings module_: Will have to look into this tonight/this afternoon when I get where I can. It should already be setup completely.

_Place Basic Medical Settings module + configure_: Should be in mission already.

_Place Medical Settings module + configure_: Will have to look into this tonight/this afternoon when I get where I can. It should already be setup completely.

_Set Medic Class not put in player inits_: It should be set in the TF Siren loadouts. Don't have them here with me to take a look at them and see what they are.

_Set Medical Facility not synced to anything_: Medical facility to be set up with the building up the slope away from the TF Siren spawn point at shoreline.

**Comment by coachwn** [comment]
V03 up for testing. Redid medical since it wasn't showing up. Also reset init files for individual units to make sure they were were working correctly. Testing locally works but haven't had a chance to test on server.

**Comment by coachwn** [comment]
Not worried about TFAR today. 

Ambient vehicles are already in via the modules; trying to dial back the number of vehicles that are spawning around the area to get a good balance. 

Going to look at various empty boxes to have for IND units to steal/grab. Also looking at ways to bobby trap those same boxes via random triggers.
