### ISSUE TITLE
Recode all Blufor SOF types to limited equipment per a FID mission set with limited resupply.

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Tanoa-Takedown#2]
Need to ensure all SOF types have enough equipment to get mission started and then have to be self sufficient until resupply can be established.

**Comment by coachwn** [comment]
Already using last good .sqf from Swift Justice but working on coding all uniforms for all SOF types to refelct tropical multicam. Using VSM and Spec4Gear as well as SMA weapons....not using RHS or HLC or NI for anything. Would like to start pushing away from that coding nightmare if at all possible.

**Comment by FoxKilo** [comment]
I'm currently doing loadouts. Will have majority of them setup by the end of tonight. Will finish in the AM

**Comment by coachwn** [comment]
I have the file complete already just haven't uploaded it.

**Comment by FoxKilo** [comment]
Complete as in the mission is ready to go? Just need loadouts and settings?

**Comment by coachwn** [comment]
Load outs are 100% just need to upload for final check.

**Comment by FoxKilo** [comment]
Alright i'm pushing through the last of our loadouts now as you can see. Once you're done I can stay awake and maybe get this up on the test server?

**Comment by FoxKilo** [comment]
SF loadouts complete. Verifying them right now to check for errors.

**Comment by FoxKilo** [comment]
All loadouts verified and optimised for the modpack.

**Comment by FoxKilo** [comment]
Scratch that. Updated modlist from 29 to 41 mods. Will have to see what new weapons and scopes/attachments will add to the loadouts. Will get them done within the next few hours of this post.

**Comment by FoxKilo** [comment]
Added SF humvee script to be used in whatever vehicle we have. Be advised script isn't finished as can't find counterparts for missing RHS items/launchers etc

**Comment by coachwn** [comment]
Rebuilt SOF teams with base amounts given by Fox. Will have updated version ASAP for testing.

**Comment by coachwn** [comment]
Opening issue again since I am going to start redoing mission and will have bugs for this...no doubt.
