### ISSUE TITLE
AI taking over bodies on player exit

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Tanoa-Takedown#20]
Not sure why this is happening but it is happening across the board in all slots. It makes it extremely difficult to manage the AI server side. We need to get into the code and modules more to see what might be causing this. Also asking on the ALiVE and BI forums as well.

**Comment by Scotty-Z** [comment]
this was a small recurring problem that we had on previous deployment (Error: No Unit) but this happen on every single log out maybe its has something to do with the player saving

**Comment by coachwn** [comment]
So BIS addressed this in a hotfix today. [https://dev.arma3.com/post/spotrep-00065](url)
