### ISSUE TITLE
V5 Issues

### ISSUE THREAD

**Issue by FoxKilo** [Spearhead-Gaming-Milsim/Tanoa-Takedown#21]
Server crashed with a 400mb+ RPT & dump file. No known cause.

replace NVGs with the non-recon type due to disappearing when not turned on

**Comment by FoxKilo** [comment]
Check console for perfmon info, server was running consistently at 11 frames after you disconnected during the major push up in the north.

Did some research into the RPT spam (Type_121 etc) and it's to do with how things are being deleted (by any script or mod) and it not registering in real time between server and client. So then when the client is requesting that object it can't find it on server side and thus produces the error message. Apparently BI is on the case and some people have work-arounds but nothing solid.

https://feedback.bistudio.com/T82940

**Comment by coachwn** [comment]
Moved beyond this issue...there are still some problems persisting and have pinned them down to Vcom calling for some weird issues with minelaying or at least that is what it looks like in Baretail. Going to close this issue and reopen on the Vcom side.
