### ISSUE TITLE
New problem now

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Tanoa-Takedown#5]
Saved mission last night with Spec4Gear removed and reloaded it and all was good to go. Tried to reload mission this morning and getting errors with 2 missing addons. Can someone give me a hint where those might be? I looked and the first one is associated with Spec4 but when I added the mod back to get the mission to load it still shows up. The 2nd missing config says it is in ACE.

=== Missing Addons ===
**C_Gen3_Characters
lbtt_Vest_config**

=== Active Addons ===
pook_SA20
pook_76N6
pook_MIM104
pook_SAM_CUP
VME_PLA_Weapons
FIR_PilotCrewPack_US
achilles_data_f_ares
VSM_HELMETS
A3_GPNVG18
VSM_Shemagh_config
SMA_Eotech_552
RH_acc
A3_Weapons_F_Mark
RH_m4_cfg
ace_tripod
ace_spottingscope
ace_kestrel4500
ace_atragmx
ace_rangecard
tfw_radios_rf3080
SMA_ROTEX_supressors
ace_chemlights
SMA_MICRO_T2
ace_vector
SMA_ELCAN_C
ace_trenches
ace_attach
ace_grenades
VSM_Vests_Config
VSM_MulticamTropic_Config
ace_parachute
mas_weapons
SMA_Weapons_Magazines
SMA_PEQ15
SMA_Weapons_Accessories
sma_vortex_optics_03
Scar_Arma3
A3_Structures_F_Exp_Industrial
sga_hover_board
A3_Air_F_Exp
A3_Air_F
A3_Boat_F_Gamma
SHG_PLA_Forces
A3_3DEN
A3_Props_F_Exp_A
cTab
A3_Structures_F_EPB
IVORY_T6A
ace_flashlights
ace_maptools
ace_goggles
task_force_radio_items
ace_optics
ace_rh_de_cfg_comp
RH_de_cfg
A3_Characters_F_Exp
ALiVE_mil_OPCOM
A3_Modules_F
ALiVE_civ_placement
ALiVE_sup_multispawn
ALiVE_mil_placement_custom
ALiVE_mil_placement
ALiVE_mil_logistics
ALiVE_mil_cqb
ALiVE_sys_aiskill
ALiVE_amb_civ_population
ALiVE_amb_civ_placement
ALiVE_sys_profile
ALiVE_SYS_playeroptions
ALiVE_sys_data
ALiVE_main
A3_Signs_F
mas_vehicleweapons_Core
A3_Characters_F
A3_Soft_F_Exp
A3_Structures_F_Exp_Infrastructure
A3_Weapons_F
SMA_Weapons
sup_recruit
A3_Weapons_F_Bootcamp
sup_loadout
mil_detection
civ_interact
amb_ambiance
ace_zeus
ace_winddeflection
ace_respawn
ace_ui
ace_tagging
ace_finger
ace_nightvision
ace_nametags
ace_microdagr
ace_map_gestures
ace_interaction
ace_hearing
ace_explosives
ace_captives
ace_map
ace_advanced_fatigue
ace_advanced_ballistics
ace_refuel
ace_rearm
ace_repair
ace_medical_menu
ace_medical
cba_main
A3_Missions_F_Curator
A3_Modules_F_Curator
A3_Structures_F_EPA
A3_Structures_F_Ind
ace_concertina_wire
ace_logistics_wirecutter
A3_Ui_F
MELB
A3_Structures_F_Wrecks
A3_Structures_F_Mil
ace_dragging
ace_cargo
A3_Props_F_Exp
A3_Supplies_F_Heli
A3_Structures_F_Heli
A3_Structures_F_Exp
A3_Structures_F
A3_Boat_F_Exp
ASH_MKVSOC

**Comment by Jmaster9999** [comment]
can you upload the mission file to github? And move the spearhead PLA mod to a separate repo?

**Comment by coachwn** [comment]
yeah going to do that now.
