### ISSUE TITLE
ACE medical

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Tanoa-Takedown#7]
Look at ACE medical modules again and turn back on to advanced. Not sure how they were missed.

**Comment by coachwn** [comment]
Not getting options for bandages other than generic bandage when wounded. Needs verification before moving forward.

**Comment by FoxKilo** [comment]
As far as I can see you don't have all the medical modules down and some options have been overlooked. will rectify with you when possible

**Comment by coachwn** [comment]
Tested ACE medical and it worked. All IND slots are coded as a medic and all TF Siren members are coded as a doctor.

**Comment by coachwn** [comment]
Works as it should.
