### ISSUE TITLE
Verify loadouts with another set of eyes

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/Tanoa-Takedown#9]
Need someone else to go over loadouts; for some reason we now have 2 loadouts of some players in the ODA loadouts and I am not sure how that happened. No substitutes for the items until 100% verified with me.

**Comment by FoxKilo** [comment]
2 loadouts are dupes either saved/loaded at the same time- by name. IR rounds and some other slight differences between the dupe files. Also need to go through and remove the numbering from the radio classes

**Comment by FoxKilo** [comment]
I'll fix the files as is, you just then need to decide which versions of the loadouts are supposed to be in-game. Will provide a list of differences here shortly

**Comment by coachwn** [comment]
"Numbering on radio classes"??? that has to be a byproduct of the mission save when it loads the loadouts to the mission.

**Comment by FoxKilo** [comment]
ISR Operator , only difference is IR rounds
ISR Sniper, no difference
ISR TL, no difference
SF Breacher, IR rounds
SF Comms, IR rounds
SF Medic, IR rounds
SF Sniper, IR rounds
SF TL, IR rounds
SF Weapons, no difference

radio numbering was probably unchecked when we originally gave you the loadouts....including the private variable not being used in the backpacks which I just fixed for all loadouts

**Comment by coachwn** [comment]
IR tracer rounds were supposed to be in the TF_Siren_Weapons_Ammo_Optics.sqf. Must have had one of the ODA loadouts open when I was copying and pasting.

**Comment by FoxKilo** [comment]
South Blade kits fixed with private variables. All loadouts should now be done.

**Comment by coachwn** [comment]
Need to take a look at JFD loadouts again. Playboy 6 not showing up with pistol mags in loadout.

**Comment by FoxKilo** [comment]
playboy 6 had missing _unit variable which wasn't loading them in. pistol ammo looks fine but may be a space issue within the vest. Can't find loadouts in mission file....seem to be config'd faction

**Comment by FoxKilo** [comment]
in-game on non-100% verion and Playboy 6 does spawn in with 2 +1 mags. May be different on your version

**Comment by coachwn** [comment]
None of the players are setup via ORBAT Creator. I am redoing the AI faction right now since several are spawning without more than 1 mag for some reason.

**Comment by coachwn** [comment]
Will fix the strobes today.

**Comment by FoxKilo** [comment]
I already did it at the time of finding the error, it was just "_v" instead of "_unit" for that line, most of the loadouts i've checked seem fine.

**Comment by coachwn** [comment]
OK will close this issue since you fixed it. Will have to update mission file with latest version. Need to start numbering versions on server so we don't get them mixed up. Start with version 03 as of today.
